home/urls.py
from django.urls import path
from . import views
app_name='home'
urlpatterns = [
	path('404', views.notfound,name='404'),
    path('', views.index,name='index'),
]

roadlink/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('account.urls')),
    path('driver/',include('driver.urls')),
    path('booking/',include('booking.urls')),
    path('repair/',include('repair.urls')),
    path('vehicle/',include('vehicle.urls')),
    path('',include('home.urls')),
    path('report/',include('report.urls'))
]

vehicle/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='vehicle'
urlpatterns = [
    path('', views.index,name='index'),
    path('addVehicle',views.addVehicle,name='addVehicle'),
    path('vehicles',views.showVehicles,name='showVehicles'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('edit/<int:id>',views.edit,name='edit'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vehicle/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Vehicle(models.Model):
    VEHICLE_STATUS_CHOICES = (
        ('B', 'Booked'),
        ('NB', 'Not Booked'),
    )
    INSURANCE_STATUS_CHOICES = (
        ('U','Updated'),
        ('NU','Not Updated'),
    )
    VEHICLE_TYPE_CHOICES = (
        ('P','Passenger'),
        ('T','Truck'),
        ('C','Construction'),
    )
    FUEL_TYPE_CHOICES = (
        ('P','Petrol'),
        ('D','Diesel'),
    )
    owner = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    cost_per_km = models.DecimalField(max_digits=20,default=0,decimal_places=2)
    price = models.DecimalField(max_digits=20,default="0",decimal_places=3)
    registration_plate = models.CharField(max_length=200,default='')
    vehicle_status = models.CharField(max_length=2,default='NB',choices=VEHICLE_STATUS_CHOICES)
    insurance_status = models.CharField(max_length=2,default='NU',choices=INSURANCE_STATUS_CHOICES)
    no_of_km_travelled = models.DecimalField(max_digits=20,default=0,decimal_places=0)
    fuel_type = models.CharField(max_length=1,default='P',choices=FUEL_TYPE_CHOICES)
    mileage = models.DecimalField(max_digits=20,default=0,decimal_places=0)
    vehicle_type = models.CharField(max_length=1,default='P',choices=VEHICLE_TYPE_CHOICES)
    image=models.ImageField(upload_to="vehicle_image",default="default.png",blank=True)

    def __str__(self):
        return self.registration_plate

vehicle/forms.py
from django import forms
from .models import Vehicle

class VehicleForm(forms.ModelForm):
    class Meta:
        model=Vehicle
        fields = ('cost_per_km','price','registration_plate','no_of_km_travelled','mileage','vehicle_type','fuel_type','insurance_status','image')

vehicle/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.template import loader
from .models import Vehicle
from .forms import VehicleForm
# Create your views here.

def index(request):
    if request.user.is_authenticated:
        form=VehicleForm()
        return render(request,'vehicle/index.html',{'form':form})
    else:
        return redirect("http://localhost:8000/home/404")

def addVehicle(request):
    if request.POST:
        form=VehicleForm(request.POST,request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.owner=request.user
            instance.save()
            success_message='Adding done'
            form=VehicleForm()
            return render(request,'vehicle/index.html',{'form':form,'success' : success_message})
    else:
        if request.user.is_authenticated:
            form=VehicleForm()
            error_message='Something went wrong error'
            return render(request,'vehicle/index.html',{ 'form' : form ,'error':error_message})

def showVehicles(request):
    if request.method=='POST' and 'searchb' in request.POST:
        search_query = request.POST.get('search_box')
        vehiclesList = Vehicle.objects.filter(registration_plate=search_query)
        return render(request,'vehicle/vehiclelist.html',{ 'vehiclesList' : vehiclesList})
    elif request.method=='POST' and 'viewallb' in request.POST: 
        vehiclesList = Vehicle.objects.all()
        return render(request,'vehicle/vehiclelist.html',{ 'vehiclesList' : vehiclesList})
    else:
        if request.user.is_authenticated:
            if request.user.is_superuser:
                vehiclesList = Vehicle.objects.all()
            else:
                vehiclesList = Vehicle.objects.filter(owner=request.user)        
            return render(request,'vehicle/vehiclelist.html',{ 'vehiclesList' : vehiclesList})
        else:
            return redirect("http://localhost:8000/home/404")

def delete(request,id):
    if request.POST:
        # form=RepairForm(request.POST)
        # if form.is_valid():
        #     instance=form.save(commit=False)
        #     instance.registeredUser=request.user
        #     instance.save()
        #     success_message='Issue Registered'
        #     form=RepairForm()
        return render(request,'vehicle/index.html',{'form':form,'user':request.user})
    else:
        if request.user.is_authenticated:
            vehicle = Vehicle.objects.get(id=id)
            vehicle.delete()
            return redirect('http://localhost:8000/vehicle/vehicles')
        else:
            return redirect("http://localhost:8000/home/404")

def edit(request,id):
    if request.method == "POST":
        vehicle=Vehicle.objects.get(id=id)
        form=VehicleForm(request.POST,request.FILES,instance=vehicle)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return redirect('http://localhost:8000/vehicle/vehicles')
    elif request.user.is_authenticated:
        vehicle=Vehicle.objects.get(id=id)
        form=VehicleForm(instance=vehicle)
        return render(request,'vehicle/vehicleEdit.html',{ 'form' : form ,'id':id})

vehicle/templates/vehicle/index.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Add New Vehicle</title>

    <!-- Bootstrap core CSS -->
    {% include 'material/includes/material_css.html' %}
    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>


</head>
<style>
#id_vehicle_type {
    margin-top : 60px;
} .welcome{
        background: #808080;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #3fada8, #808080);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #3fada8, #808080); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

    }</style>
<body>
{% if user.is_authenticated %}
    <div id="wrapper">
            {% include 'driver/navbar.html' %}


        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col s8 offset-s2">
                           {%if success %}
                            <div id="card-alert" class="card green lighten-5">
                      <div class="card-content red-text">
                        <p>{{success}}</p>
                      </div>
                    </div>
                            {% endif %}
                        <div class="card">
                                  <div class="col s12">
                      <div class="welcome card-panel z-depth-3">
                        
                          <span style="padding-left: 35%;" class="white-text"><font color="black" size="20">Add Vehicle</font>
                      </span>
                      </div>
                    </div>
                            <div class="card-content">
                            <form action="/vehicle/addVehicle" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="row">
                                    <div class="col s4 offset-s4 center">
                                        <input type="submit" class="btn" value="Add">
                                    </div>
                                </div>
                            </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
{% else %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-3">You are not logged in</h1>
    </div>
</div>
{% endif %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
</body>

</html>

vehicle/templates/vehicle/vehicleEdit.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Edit Vehicle</title>

    <!-- Bootstrap core CSS -->
    {% include 'material/includes/material_css.html' %}
    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>


</head>
<style>
#id_vehicle_type {
    margin-top : 60px;
}
</style>
<body>
{% if user.is_authenticated %}
    <div id="wrapper">
            {% include 'driver/navbar.html' %}


        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col s8 offset-s2">
                            {%if success %}
                            <div class="alert alert-success" role="alert">
                                    {{ success }}
                                  </div>
                            {% endif %}
                        <div class="card">
                            <div class="card-title center">
                                <h2>Add New Vehicle</h2>
                            </div>
                            <div class="card-content">
                            <form action="/vehicle/edit/{{id}}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="row">
                                    <div class="col s4 offset-s4 center">
                                        <input type="submit" class=" btn-large" value="Add">
                                    </div>
                                </div>
                            </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
{% else %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-3">You are not logged in</h1>
    </div>
</div>
{% endif %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
</body>

</html>

vehicle/templates/vehicle/vehiclelist.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Vehicles</title>

    {% include 'material/includes/material_css.html' %}
    <script src="{% static 'material/js/jquery.js' %}"></script>
    {% include 'material/includes/material_js.html' %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

</head>
<style>
.nav {
    margin-bottom: 20px;
}
    .card-holder{
        padding: 30px;
        padding-left: 40px;
        padding-right: 50px;
    }
    .welcome{
        background: #808080;  /* fallback for old browsers */
background: -webkit-linear-gradient(to right, #3fada8, #808080);  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to right, #3fada8, #808080); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

    }
</style>
<body>
{% if user.is_authenticated %}
    <div id="wrapper">
        {% include 'driver/navbar.html' %}
        <!-- Sidebar -->
        <!--<div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                       Road Link
                    </a>
                </li>
                <li>
                    <a href="/account/profile">Dashboard</a>
                </li>
                <li>
                    <a href="/driver">View all drivers</a>
                </li>
                <li>
                    <a href="/driver">Add driver</a>
                </li>
                <li>
                    <a href="/vehicle/vehicles">View your vehicles</a>
                </li>
                <li>
                    <a href="#">View all trips</a>
                </li>
                <li>
                    <a href="/vehicle/addVehicle">Add vehicle</a>
                </li>
                <li>
                    <a href="/repair">Repair</a>
                </li>
                <li>
                    <a href="/repair/issues">Repair List</a>
                </li>
                <li>
                    <a href="#">View report</a>
                </li>
                <li>
                    <form action="/account/logout" method="POST">
                    {%csrf_token%}
                    <input type="submit" class="btn btn-primary" value="Logout">
                </form>
                </li>
            </ul>
        </div>-->
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                
                <div class="row">
                    
                    <div class="col-md-12">
                            {%if success %}
                            <div class="alert alert-success" role="alert">
                                    {{ success }}
                                  </div>
                            {% endif %}
                        <div class="card">
                            <div class="card-header">
                                <div class="col s12">
                      <div class="welcome card-panel z-depth-3">
                        
                          <span style="padding-left: 43%;" class="white-text"><font color="black" size="20">Vehicles</font>
                      </span>
                      </div>
                    </div>
                                <!-- <form method="POST" style="margin: 0">
                                    {% csrf_token %}
                                    <input  id="search_box" type="text" name="search_box"  placeholder="Search..." >
                                    <button id="search_submit" type="submit" name="searchb" class="btn btn-success">Submit</button>
                                    <button id="search_submit" type="submit" name="viewallb" class="btn btn-primary">View All</button>
                                </form> -->
                            </div>
                            <div class="card-body text-center">
                                <div class="row">
                                    {% for vehicle in vehiclesList %}
                                    <div class="col s8 m3">
                                      <div class="card">
                                        <div class="card-image">
                                          <img width="300px" height="300px" src="{{vehicle.image.url }}">
                                          <span class="card-title">{{vehicle.registration_plate}}</span>
                                        </div>
                                        
                                        <div class="card-action">
                                          <a class="waves-effect waves-light btn modal-trigger" onclick="$('#modal1').modal('open');">More Details</a>
                                           <a href="/vehicle/delete/{{vehicle.id}}"><button class=" btn">Delete</button></a>
                                       <a href="/vehicle/edit/{{vehicle.id}}"><button style="margin-top: 2%;" class=" btn">edit</button></a>
                                        </div>
                                          <!-- Modal Structure -->
                                          <div id="modal1" class="modal">
                                            <div class="modal-content">
                                              <h4>{{vehicle.registration_plate}}</h4>
                                              <ul class="collection">
                                                                    {% if user.is_superuser %}
                                                                        <li class="collection-item">Owner :{{vehicle.owner}}</li>
                                                                    {% endif %}
                                                                  <li class="collection-item">Price :{{vehicle.price}}</li>
                                                                  <li class="collection-item">Cost per km :{{vehicle.cost_per_km}}</li>
                                                                  <li class="collection-item">No of Kms Travelled : {{vehicle.no_of_km_travelled}}</li>
                                                                  {% if vehicle.fuel_type == "P" %}
                                                                  <li class="collection-item">Fuel Type : Petrol</li>
                                                                  {% else %}
                                                                  <li class="collection-item">Fuel Type : Diesel</li>    
                                                                  {% endif %}
                                                                  <li class="collection-item">Mileage : {{vehicle.mileage}}</li>
                                                                </ul>
                                            </div>
                                            <div class="modal-footer">
                                              <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
                                            </div>
                                          </div>
          
                                      </div>
                                    </div>
                                    {% endfor %}
                                  </div>
                                   
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->
{% else %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-3">You are not logged in</h1>
    </div>
</div>
{% endif %}
    <!-- Bootstrap core JavaScript -->
   
    <script type="text/javascript">
               
              $(document).ready(function(){
                $('.modal').modal();
              });
          
    </script>
    <!-- Menu Toggle Script -->
    

</body>

</html>